apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-build.v0.4.0
  annotations:
    alm-examples: '[{"apiVersion":"build.knative.dev/v1alpha1","kind":"Build","metadata":{"name":"sample-build"},"spec":{"source":{"git":{"url":"https://github.com/knative/build.git","revision":"master"}},"steps":[{"image":"fedora","args":["cat", "README.md"]}]}}]'
spec:
  displayName: Knative Build
  description: |
    Kubernetes-native Build resource
  version: 0.4.0
  maturity: alpha
  replaces: knative-build.v0.3.0

  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: build-controller
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          - secrets
          - events
          - serviceaccounts
          - configmaps
          - services
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds/status
          - buildtemplates/status
          - clusterbuildtemplates/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - caching.internal.knative.dev
          resources:
          - images
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - patch
          - watch
        - apiGroups:
          - policy
          resourceNames:
          - knative-build
          resources:
          - podsecuritypolicies
          verbs:
          - use

        # The above rules are from upstream. The remaining are
        # required for either OpenShift or our operator

        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
          - anyuid
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - build.knative.dev
          resources:
          - '*/finalizers'
          verbs:
          - update
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - create
          - patch
          - get
        - apiGroups:
          - build.knative.dev
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - create
          - update
          - delete

      deployments:
      - name: knative-build-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: knative-build-operator
          template:
            metadata:
              labels:
                name: knative-build-operator
            spec:
              serviceAccountName: build-controller
              containers:
                - name: knative-build-operator
                  image: quay.io/jcrossley3/knative-build-operator:0.4.0
                  command:
                  - knative-build-operator
                  args:
                    - --olm
                    - --install
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: "knative-build-operator"

  customresourcedefinitions:
    owned:
      - description: Create and run on-cluster processes to completion
        displayName: Build
        kind: Build
        name: builds.build.knative.dev
        version: v1alpha1
        statusDescriptors:
          - description: The Pod this Build ran on
            displayName: Build Pod
            path: cluster.podName
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:Pod'
          - description: The start time of the Build
            displayName: Start Time
            path: startTime
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The completion time of the Build
            displayName: Completion Time
            path: completionTime
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The conditions of this Build
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
      - description: Encapsulates a configurable, reusable build process
        displayName: Build Template
        kind: BuildTemplate
        name: buildtemplates.build.knative.dev
        version: v1alpha1
      - description: Encapsulates a cluster-scoped build process
        displayName: Cluster Build Template
        kind: ClusterBuildTemplate
        name: clusterbuildtemplates.build.knative.dev
        version: v1alpha1
      - description: Knative Build Installation
        displayName: Install Operator
        kind: Install
        name: installs.build.knative.dev
        version: v1alpha1
