apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-serving.v0.3.0
spec:
  displayName: Knative Serving
  description: |
    Knative Serving builds on Kubernetes and Istio to support deploying and serving of serverless applications and functions
  version: 0.3.0
  maturity: alpha
  replaces: knative-serving.v0.2.2
  
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: controller
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          - secrets
          - configmaps
          - endpoints
          - services
          - events
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - ingresses
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - deployments/scale
          - statefulsets
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - serving.knative.dev
          resources:
          - configurations
          - routes
          - revisions
          - services
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - serving.knative.dev
          resources:
          - configurations/status
          - routes/status
          - revisions/status
          - services/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - autoscaling.internal.knative.dev
          resources:
          - podautoscalers
          - podautoscalers/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - caching.internal.knative.dev
          resources:
          - images
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - networking.internal.knative.dev
          resources:
          - clusteringresses
          - clusteringresses/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - networking.istio.io
          resources:
          - virtualservices
          - gateways
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch

        # The above rules are from upstream. The remaining are
        # required for OpenShift

        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
          - anyuid
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - serving.knative.dev
          - networking.internal.knative.dev
          resources:
          - '*/finalizers'
          verbs:
          - update

      deployments:
      - name: activator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: activator
              role: activator
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                app: activator
                role: activator
            spec:
              containers:
              - args:
                - -logtostderr=false
                - -stderrthreshold=FATAL
                env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: gcr.io/knative-releases/github.com/knative/serving/cmd/activator@sha256:8d1696bb0e5fe143b0cb273f169b1f2841f71e48490247b8cad35bc65b2b2d6e
                name: activator
                ports:
                - containerPort: 8080
                  name: activator-port
                - containerPort: 9090
                  name: metrics-port
                resources:
                  limits:
                    cpu: 200m
                    memory: 600Mi
                  requests:
                    cpu: 20m
                    memory: 60Mi
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
                - mountPath: /etc/config-observability
                  name: config-observability
              serviceAccountName: controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging
              - configMap:
                  name: config-observability
                  optional: true
                name: config-observability

      - name: autoscaler
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: autoscaler
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                app: autoscaler
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/serving/cmd/autoscaler@sha256:9d2db2ba2607b46af18a79c7cdf532d84b0aac34c1a418d6d4a239f8d8271566
                name: autoscaler
                ports:
                - containerPort: 8080
                  name: websocket
                - containerPort: 9090
                  name: metrics
                resources:
                  limits:
                    cpu: 300m
                    memory: 400Mi
                  requests:
                    cpu: 30m
                    memory: 40Mi
                volumeMounts:
                - mountPath: /etc/config-autoscaler
                  name: config-autoscaler
                - mountPath: /etc/config-logging
                  name: config-logging
                - mountPath: /etc/config-observability
                  name: config-observability
              serviceAccountName: controller
              volumes:
              - configMap:
                  name: config-autoscaler
                name: config-autoscaler
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging
              - configMap:
                  name: config-observability
                  optional: true
                name: config-observability

      - name: controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: controller
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: controller
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/serving/cmd/controller@sha256:5a5a0d5fffe839c99fc8f18ba028375467fdcd83cbee9c7015c1a58d01ca6929
                name: controller
                ports:
                - containerPort: 9090
                  name: metrics
                resources:
                  limits:
                    cpu: 1000m
                    memory: 1000Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/master/etc/hacks/knative-serving-0.3.0.yaml']
              serviceAccountName: controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

      - name: webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webhook
              role: webhook
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: webhook
                role: webhook
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/serving/cmd/webhook@sha256:4a91a1991db282ea62426023bae4ae3ea331b10e2b4ac20f4581afdd90c6bdce
                name: webhook
                resources:
                  limits:
                    cpu: 200m
                    memory: 200Mi
                  requests:
                    cpu: 20m
                    memory: 20Mi
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

  customresourcedefinitions:
    owned:
      - kind: Configuration
        name: configurations.serving.knative.dev
        description: "Maintains the desired state for your deployment. It provides a clean separation between code and configuration and follows the Twelve-Factor App methodology. Modifying a configuration creates a new revision."
        displayName: Configuration
        version: v1alpha1
        statusDescriptors:
          - description: The latest Revision for this Configuration
            displayName: Latest Revision
            path: latestCreatedRevisionName
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The conditions of this Configuration
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
      - kind: Revision
        name: revisions.serving.knative.dev
        description: "A point-in-time snapshot of the code and configuration for each modification made to the workload. Revisions are immutable objects and can be retained for as long as useful."
        displayName: Revision
        version: v1alpha1
      - kind: Route
        name: routes.serving.knative.dev
        description: "Maps a network endpoint to a one or more revisions. You can manage the traffic in several ways, including fractional traffic and named routes."
        displayName: Knative Route
        version: v1alpha1
      - kind: Service
        name: services.serving.knative.dev
        description: "Automatically manages the whole lifecycle of your workload. It controls the creation of other objects to ensure that your app has a route, a configuration, and a new revision for each update of the service. Service can be defined to always route traffic to the latest revision or to a pinned revision."
        displayName: Knative Service
        version: v1alpha1
        statusDescriptors:
          - description: The external domain name for this Service
            displayName: External Domain
            path: domain
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The in-cluster domain name for this Service
            displayName: Internal Domain
            path: address.hostname
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The latest Revision for this Service
            displayName: Latest Revision
            path: latestCreatedRevisionName
            x-descriptors:
              - 'urn:alm:descriptor:text'
          - description: The conditions of this Service
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
      - description: A cached build image?
        displayName: Image
        kind: Image
        name: images.caching.internal.knative.dev
        version: v1alpha1
      - description: A cluster ingress?
        displayName: Cluster Ingress
        kind: ClusterIngress
        name: clusteringresses.networking.internal.knative.dev
        version: v1alpha1
      - description: A pod autoscaler?
        displayName: Pod Autoscaler
        kind: PodAutoscaler
        name: podautoscalers.autoscaling.internal.knative.dev
        version: v1alpha1
